# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://Istaarkk.github.io/cybersecurity-notes/"
defaultContentLanguage = "fr"
summaryLength = 0

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
hasCJKLanguage = true

buildDrafts = false
buildFuture = false

enableEmoji = true

googleAnalytics = "G-PEDMYR1V0K"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10

# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "WriteUps"
  pageRef = "writeups"
  weight = 10

[[main]]
  name = "Veille"
  pageRef = "veille"
  weight = 20

[[main]]
  name = "Outils"
  pageRef = "outils"
  weight = 30

# -- Sub Menu --
[[main.children]]
  name = "Web Hacking"
  pageRef = "writeups/web"
  weight = 11

[[main.children]]
  name = "Pwn & Exploitation"
  pageRef = "writeups/pwn"
  weight = 12

# Ajoute les autres sous-menus selon ton config.yaml
