baseURL: "https://istaarkk.github.io/"
languageCode: "en-us"
title: "Cybersecurity Notes"

params:
  description: "Security research and CTF writeups"
  author: "istark"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: monokai

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writeups
      url: /writeups/
      weight: 2
    - name: About
      url: /about/
      weight: 3
