baseURL: "https://istaarkk.github.io/"
languageCode: "fr-fr"
title: "Notes & Recherches Cybersécurité"
theme: "hugo-theme-stack"

params:
  mainSections:
    - notes
    - recherches
    - veille
    - outils
  # Disable search
  search:
    enable: false
  # Code highlighting
  code:
    copy: true
    highlight: true
    lineNumbers: false
    theme: "monokai"
  # Disable search in navbar
  navbar:
    search: false

menu:
  main:
    - identifier: notes
      name: Notes
      url: /notes/
      weight: 10
    - identifier: veille
      name: Veille
      url: /veille/
      weight: 20
    - identifier: outils
      name: Outils
      url: /outils/
      weight: 30

module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3 