baseURL: "https://Istaarkk.github.io/cybersecurity-notes/"
languageCode: "fr-fr"
title: "WriteUps & Recherches Cybersécurité"
theme: "cybernotes"

params:
  mainSections:
    - writeups
    - veille
    - outils
  # Disable search
  search:
    enable: false
  # Code highlighting
  code:
    copy: true
    highlight: true
    lineNumbers: false
    theme: "monokai"
  # Disable search in navbar
  navbar:
    search: false

menu:
  main:
    - identifier: writeups
      name: WriteUps
      url: /writeups/
      weight: 10
      children:
        - identifier: pwnme-junior
          name: PwnMe Junior
          url: /writeups/pwnme-junior/
          weight: 10
    - identifier: veille
      name: Veille
      url: /veille/
      weight: 20
    - identifier: outils
      name: Outils
      url: /outils/
      weight: 30 